
export interface VideoModel {
  id: number;
  channelName: string;
  uri: string;
  caption: string;
  musicName: string;
  likes: number;
  comments: number;
  avatarUri: string;
}

export default [
  {
    id: 1,
    channelName: 'cutedog',
    uri: require('../../../assets/video/16.mp4'),
    caption: 'Cute dog shaking hands #cute #puppy',
    musicName: 'Song #1',
    likes: 4321,
    comments: 2841,
    avatarUri: 'https://wallpaperaccess.com/full/1669289.jpg',
  },
  {
    id: 2,
    channelName: 'meow',
    uri: require('../../../assets/video/17.mp4'),
    caption: 'Doggies eating candy #cute #puppy',
    musicName: 'Song #2',
    likes: 2411,
    comments: 1222,
    avatarUri: 'https://wallpaperaccess.com/thumb/266770.jpg',
  },
  {
    id: 3,
    channelName: 'yummy',
    uri: require('../../../assets/video/14.mp4'),
    caption: 'Brown little puppy #cute #puppy',
    musicName: 'Song #3',
    likes: 3100,
    comments: 801,
    avatarUri: 'https://wallpaperaccess.com/thumb/384178.jpg',
  },
  {
    id: 4,
    channelName: 'puppyparadise',
    uri: require('../../../assets/video/12.mp4'),
    caption: 'Puppy playing with a ball #fun #puppy',
    musicName: 'Song #4',
    likes: 5560,
    comments: 4200,
    avatarUri: 'https://wallpaperaccess.com/thumb/1788377.jpg',
  },
  {
    id: 5,
    channelName: 'fluffy_tales',
    uri: require('../../../assets/video/13.mp4'),
    caption: 'Fluffy puppy taking a nap #cute #puppy',
    musicName: 'Song #5',
    likes: 4721,
    comments: 2310,
    avatarUri: 'https://wallpaperaccess.com/full/1087107.jpg',
  },
  {
    id: 6,
    channelName: 'puppylove',
    uri: require('../../../assets/video/15.mp4'),
    caption: 'Playful puppy running around #playful #puppy',
    musicName: 'Song #6',
    likes: 6090,
    comments: 3500,
    avatarUri: 'https://wallpaperaccess.com/thumb/1639840.jpg',
  },
  {
    id: 7,
    channelName: 'barkingfun',
    uri: require('../../../assets/video/16.mp4'),
    caption: 'Dog barking at a butterfly #cute #puppy',
    musicName: 'Song #7',
    likes: 5120,
    comments: 1500,
    avatarUri: 'https://wallpaperaccess.com/thumb/1478458.jpg',
  },
  {
    id: 8,
    channelName: 'petantics',
    uri: require('../../../assets/video/18.mp4'),
    caption: 'Puppy tries to catch its tail #funny #puppy',
    musicName: 'Song #8',
    likes: 7900,
    comments: 4320,
    avatarUri: 'https://wallpaperaccess.com/full/1034475.jpg',
  },
  {
    id: 9,
    channelName: 'cutedoggo',
    uri: require('../../../assets/video/19.mp4'),
    caption: 'Adorable puppy with a hat #cute #puppy',
    musicName: 'Song #9',
    likes: 3890,
    comments: 1780,
    avatarUri: 'https://wallpaperaccess.com/thumb/1897451.jpg',
  },
  {
    id: 10,
    channelName: 'dogvids',
    uri: require('../../../assets/video/12.mp4'),
    caption: 'Doggies in a dog park #fun #puppy',
    musicName: 'Song #10',
    likes: 6340,
    comments: 2990,
    avatarUri: 'https://wallpaperaccess.com/thumb/1221850.jpg',
  },
  {
    id: 11,
    channelName: 'doggo_daily',
    uri: require('../../../assets/video/13.mp4'),
    caption: 'Puppy and kitten playing together #cute #friendship',
    musicName: 'Song #11',
    likes: 5240,
    comments: 3150,
    avatarUri: 'https://wallpaperaccess.com/full/1701973.jpg',
  },
  {
    id: 12,
    channelName: 'puppylife',
    uri: require('../../../assets/video/14.mp4'),
    caption: 'Playful pup jumping around #fun #puppy',
    musicName: 'Song #12',
    likes: 6950,
    comments: 4200,
    avatarUri: 'https://wallpaperaccess.com/thumb/2283885.jpg',
  },
  {
    id: 13,
    channelName: 'furryfriends',
    uri: require('../../../assets/video/15.mp4'),
    caption: 'Puppy making new friends #cute #friends',
    musicName: 'Song #13',
    likes: 8000,
    comments: 5100,
    avatarUri: 'https://wallpaperaccess.com/full/2121759.jpg',
  },
  {
    id: 14,
    channelName: 'dog_tricks',
    uri: require('../../../assets/video/16.mp4'),
    caption: 'Dog doing tricks #smart #puppy',
    musicName: 'Song #14',
    likes: 3720,
    comments: 1880,
    avatarUri: 'https://wallpaperaccess.com/thumb/2101970.jpg',
  },
  {
    id: 15,
    channelName: 'puppyplay',
    uri: require('../../../assets/video/17.mp4'),
    caption: 'Dog and owner playing fetch #fun #puppy',
    musicName: 'Song #15',
    likes: 9210,
    comments: 5200,
    avatarUri: 'https://wallpaperaccess.com/full/539053.jpg',
  },
  {
    id: 16,
    channelName: 'doglovers',
    uri: require('../../../assets/video/18.mp4'),
    caption: 'Puppy cuddling with owner #cute #puppy',
    musicName: 'Song #16',
    likes: 7680,
    comments: 4100,
    avatarUri: 'https://wallpaperaccess.com/thumb/1260915.jpg',
  },
  {
    id: 17,
    channelName: 'fluffytails',
    uri: require('../../../assets/video/19.mp4'),
    caption: 'Puppy chasing butterflies #funny #cute',
    musicName: 'Song #17',
    likes: 6530,
    comments: 3100,
    avatarUri: 'https://wallpaperaccess.com/full/367649.jpg',
  },
  {
    id: 18,
    channelName: 'furbabies',
    uri: require('../../../assets/video/20.mp4'),
    caption: 'Cute puppy eating snacks #delicious #puppy',
    musicName: 'Song #18',
    likes: 8320,
    comments: 4520,
    avatarUri: 'https://wallpaperaccess.com/thumb/1893150.jpg',
  },
  {
    id: 19,
    channelName: 'dogchannel',
    uri: require('../../../assets/video/21.mp4'),
    caption: 'Dogs running freely in the park #joyful #puppy',
    musicName: 'Song #19',
    likes: 7020,
    comments: 2890,
    avatarUri: 'https://wallpaperaccess.com/thumb/2228947.jpg',
  },
  {
    id: 20,
    channelName: 'pupvibes',
    uri: require('../../../assets/video/22.mp4'),
    caption: 'Puppy playing in the snow #fun #puppy',
    musicName: 'Song #20',
    likes: 8990,
    comments: 5700,
    avatarUri: 'https://wallpaperaccess.com/thumb/2156590.jpg',
  },
];
